CREATE TABLE UF
(
	ID		INT			NOT NULL,
	SIGLA 	VARCHAR(2)	NOT NULL,
	NOME	VARCHAR(50)	NOT NULL,
	REGIAO	VARCHAR(50)	NOT NULL,
	CONSTRAINT	PK_UF PRIMARY KEY (ID)
);

CREATE TABLE CIDADE
(
	ID		INT				NOT NULL,
	ID_UF	INT				NOT NULL,
	NOME	VARCHAR(200)	NOT NULL,
	CONSTRAINT PK_CIDADE PRIMARY KEY (ID), 
	CONSTRAINT FK_CIDADE_UF FOREIGN KEY (ID_UF)
	REFERENCES UF (ID)
);

CREATE TABLE DISTRITO
(
	ID			INT				NOT NULL,
	ID_CIDADE	INT				NOT NULL,
	NOME		VARCHAR(200)	NOT NULL,
	CONSTRAINT	PK_DISTRITO PRIMARY KEY (ID),
	CONSTRAINT FK_DISTRITO_CIDADE FOREIGN KEY (ID_CIDADE)
	REFERENCES CIDADE (ID)	
);
