-- COMENTÁRIO DE LINHA

/*
 * COMENTÁRIO DE BLOCO
 * 
 */

-- SQL (ANSI) => DDL (Data Definition Language) (CREATE, DROP, ALTER) 
-- + DML (Data Manipulation Language) (INSERT, UPDATE, DELETE, SELECT)
 
-- Criação de banco de dados
CREATE DATABASE BD_SQL_GAMMA;

-- Seleção de um determinado banco de dados
USE BD_SQL_GAMMA;


/* -- EXEMPLIFICAçãO DE PK (PRIMARY KEY) COMPOSTA
CREATE TABLE CLIENTE 
(
	UF		VARCHAR(2)		NOT NULL,
	RG		VARCHAR(8)		NOT NULL, 
	.
	.
	.
	,
	CONSTRAINT PK_CLIENTE PRIMARY KEY (UF, RG)
);

-- EXEMPLIFICAçãO DE RELACIONAMENTO 1 .. 1
CREATE TABLE CLIENTE_COMPL
(
	ID_CLIENTE		INT			NOT NULL,
	.
	.
	.
	,
	CONSTRAINT PK_CLIENTE_COMPL PRIMARY KEY (ID_CLIENTE),
	CONSTRAINT FK_CLIENTE_COMPL_CLIENTE FOREIGN KEY (ID_CLIENTE)
	REFERENCES CLIENTE (ID)
);

-- EXEMPLIFICAçãO DE RELACIONAMENTO N .. N
CREATE TABLE PRODUTO
(
	ID			INT			NOT NULL,
	.
	.
	.
	,
	CONSTRAINT PK_PRODUTO PRIMARY KEY (ID)
);

CREATE TABLE CATEGORIA
(
	ID			INT			NOT NULL,
	.
	.
	.
	,
	CONSTRAINT PK_CATEGORIA PRIMARY KEY (ID)
);

CREATE TABLE PRODUTO_CATEGORIA
(
	ID_PRODUTO		INT		NOT NULL,
	ID_CATEGORIA	INT 	NOT NULL,
	CONSTRAINT PK_PRODUTO_CATEGORIA PRIMARY KEY (ID_PRODUTO, ID_CATEGORIA),
	CONSTRAINT FK_PRODUTO_CATEGORIA_CATEGORIA FOREIGN KEY (ID_CATEGORIA)
	REFERENCES CATEGORIA (ID),
	CONSTRAINT FK_PRODUTO_CATEGORIA_PRODUTO FOREIGN KEY (ID_PRODUTO)
	REFERENCES PRODUTO (ID)
); */


/* Criação de um Banco de Dados para gerir armazenamento de 
CLIENTES, com telefones de contato, documentos e endereços,
e gestão de armazenamento de cupons fiscais de venda ao 
consumidor final.
*/

CREATE TABLE CLIENTE
(
	ID			INT				NOT NULL IDENTITY(1, 1),
	NOME		VARCHAR(50)		NOT NULL,
	SOBRENOME	VARCHAR(100)	NULL,
	DT_NASC		DATE			NULL,
	CONSTRAINT PK_CLIENTE PRIMARY KEY (ID)
);

CREATE TABLE CLIENTE_TELEFONES
(
	ID			INT			NOT NULL IDENTITY(1, 1),
	ID_CLIENTE	INT			NOT NULL, -- FK (CHAVE ESTRANGEIRA)
	DDD			VARCHAR(3)	NOT NULL,
	N_TELEFONE	VARCHAR(9)	NOT NULL,
	CONSTRAINT PK_CLIENTE_TELEFONES PRIMARY KEY (ID),
	CONSTRAINT FK_CLIENTE_TELEFONES_CLIENTE FOREIGN KEY (ID_CLIENTE)
	REFERENCES CLIENTE (ID)
);

CREATE TABLE TIPO_DOCUMENTOS
(
	ID			INT				NOT NULL IDENTITY(1, 1),
	NOME		VARCHAR(50)		NOT NULL,
	DESCRICAO	VARCHAR(500)	NULL,
	CONSTRAINT PK_TIPO_DOCUMENTOS PRIMARY KEY (ID)
);

CREATE TABLE CLIENTE_DOCUMENTOS
(
	ID					INT			NOT NULL IDENTITY(1, 1),
	ID_CLIENTE			INT			NOT NULL,
	ID_TIPO_DOCUMENTOS	INT			NOT NULL,
	N_DOCUMENTO			VARCHAR(50)	NOT NULL,
	CONSTRAINT PK_CLIENTE_DOCUMENTOS PRIMARY KEY (ID),
	CONSTRAINT FK_CLIENTE_DOCUMENTOS_CLIENTE FOREIGN KEY (ID_CLIENTE)
	REFERENCES CLIENTE (ID),
	CONSTRAINT FK_CLIENTE_DOCUMENTOS_TIPO_DOCUMENTOS FOREIGN KEY (ID_TIPO_DOCUMENTOS)
	REFERENCES TIPO_DOCUMENTOS (ID)
);


CREATE TABLE TIPO_ENDERECOS
(
	ID				INT				NOT NULL IDENTITY(1, 1),
	NOME			VARCHAR(50)		NOT NULL,
	DESCRICAO		VARCHAR(500)	NULL,
	CONSTRAINT PK_TIPO_ENDERECOS PRIMARY KEY (ID)
);

CREATE TABLE UF
(
	ID			INT			NOT NULL IDENTITY(1, 1),
	NOME		VARCHAR(50)	NOT NULL,
	SIGLA		VARCHAR(2)	NOT NULL,
	CONSTRAINT PK_UF PRIMARY KEY (ID)
);

CREATE TABLE CIDADE
(
	ID			INT			NOT NULL IDENTITY(1, 1),
	ID_UF		INT			NOT NULL,
	NOME		VARCHAR(50)	NOT NULL,
	N_IBGE		VARCHAR(8)	NULL,
	CONSTRAINT PK_CIDADE PRIMARY KEY (ID),
	CONSTRAINT FK_CIDADE_UF FOREIGN KEY (ID_UF)
	REFERENCES UF (ID)
);

CREATE TABLE CLIENTE_ENDERECOS
(
	ID					INT				NOT NULL IDENTITY(1, 1),
	ID_CLIENTE			INT				NOT NULL,
	ID_TIPO_ENDERECOS	INT				NOT NULL,
	ID_CIDADE			INT				NOT NULL,
	TIPO_LOGRADOURO		VARCHAR(20)		NOT NULL,
	NOME_LOGRADOURO		VARCHAR(100)	NOT NULL,
	NUMERO				VARCHAR(6)		NULL,
	COMPLEMENTO			VARCHAR(20)		NULL,
	BAIRRO				VARCHAR(50)		NOT NULL,
	CEP					VARCHAR(8)		NULL,
	CONSTRAINT PK_CLIENTE_ENDERECOS PRIMARY KEY (ID),
	CONSTRAINT FK_CLIENTE_ENDERECOS_CLIENTE FOREIGN KEY (ID_CLIENTE)
	REFERENCES CLIENTE (ID),
	CONSTRAINT FK_CLIENTE_ENDERECOS_TIPO_ENDERECO FOREIGN KEY (ID_TIPO_ENDERECOS)
	REFERENCES TIPO_ENDERECOS (ID),
	CONSTRAINT FK_CLIENTE_ENDERECOS_CIDADE FOREIGN KEY (ID_CIDADE)
	REFERENCES CIDADE (ID)
);

CREATE TABLE PRODUTO
(
	ID			INT				NOT NULL IDENTITY(1, 1),
	NOME		VARCHAR(50)		NOT NULL,
	QUANTIDADE	DECIMAL(10, 2)	NOT NULL,
	VALOR		DECIMAL(10, 2)	NOT NULL,
	DESCRICAO	VARCHAR(500)	NULL,
	CONSTRAINT PK_PRODUTO PRIMARY KEY (ID)
);

CREATE TABLE CUPOM_FISCAL
(
	ID			INT			NOT NULL IDENTITY(1, 1),
	ID_CLIENTE	INT			NOT NULL,
	DATA		DATETIME	NOT NULL,
	CONSTRAINT PK_CUPOM_FISCAL PRIMARY KEY (ID),
	CONSTRAINT FK_CUPOM_FISCAL FOREIGN KEY (ID_CLIENTE)
	REFERENCES CLIENTE (ID)
);

CREATE TABLE CUPOM_FISCAL_ITENS
(
	ID 			INT				NOT NULL IDENTITY(1, 1),
	ID_CUPOM	INT				NOT NULL,
	ID_PRODUTO	INT				NOT NULL,
	VALOR		DECIMAL(10, 2)	NOT NULL,
	QUANTIDADE	DECIMAL(10, 2)	NOT NULL,
	CONSTRAINT PK_CUPOM_FISCAL_ITENS PRIMARY KEY (ID),
	CONSTRAINT FK_CUPOM_FISCAL_ITENS_CUPOM_FISCAL FOREIGN KEY (ID_CUPOM)
	REFERENCES CUPOM_FISCAL (ID),
	CONSTRAINT FK_CUPOM_FISCAL_ITENS_PRODUTO FOREIGN KEY (ID_PRODUTO)
	REFERENCES PRODUTO (ID)
);










